logging:
  level: debug
  path:  D:/logs
server:
  port: 9000

#jackson返回日期格式化

spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    joda-date-time-format: yyyy-MM-dd HH:mm:ss
    locale: zh_CN
    time-zone: GMT+8
  # mysql config
  # Druid 数据库连接池配置
  # WebStatFilter配置，说明请参考Druid Wiki，配置_配置WebStatFilter
  # Spring监控配置，说明请参考Druid Github Wiki，Spring监控AOP切入点，如x.y.z.service.*,配置多个英文逗号分隔
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/common-admin?characterEncoding=utf-8
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat,wall,log4j
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      web-stat-filter:
        url-pattern: /*
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'
      aop-patterns: com.common.system.service.*

#mapper.xml存放位置，必须。

mybatis:
  mapper-locatio: classpath:/mapper/*.xml
mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
